version: '3.8'

services:
  backend:
    container_name: helios-backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      WORKSPACE_DIR: ${WORKSPACE_DIR}
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
      - ./workspaces:/workspaces
    depends_on:
      - postgres
      - redis
    command: npm run dev

  postgres:
    container_name: helios-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: helios-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  frontend:
    container_name: helios-frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
      - ./packages/frontend/.env:/app/.env
    depends_on:
      - backend

  pgadmin:
    container_name: helios-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:
