version: '3.8'

services:
  backend:
    container_name: helios-backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://helios:helios123@postgres:5432/helios_db
      REDIS_URL: redis://redis:6379
      SUPABASE_URL: https://kaeydovooyaxczctsmas.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZXlkb3Zvb3lheGN6Y3RzbWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTQ0NjIsImV4cCI6MjA2NTYzMDQ2Mn0.zff2YLM-vJRfvaJvNrVAywNmgGurEQ9ZW8t_jKyE6DI
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZXlkb3Zvb3lheGN6Y3RzbWFzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDA1NDQ2MiwiZXhwIjoyMDY1NjMwNDYyfQ.FfFHyVLrkDkSNjvIMtSlf6lbWeboMTsPx30v1K0MAi4
      SUPABASE_DB_URL: postgresql://postgres:InstaBidsSystem321@db.kaeydovooyaxczctsmas.supabase.co:5432/postgres
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
      - ./workspaces:/workspaces
    depends_on:
      - postgres
      - redis
    command: npm run dev

  postgres:
    container_name: helios-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: helios
      POSTGRES_PASSWORD: helios123
      POSTGRES_DB: helios_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./packages/backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: helios-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  frontend:
    container_name: helios-frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  pgadmin:
    container_name: helios-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:
